name: WASM to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Check clang-format
        run: |
          clang-format --dry-run --Werror -style=file \
          $(find src include -type f \( -name '*.cpp' -o -name '*.hpp' \))

  build:
    needs: format

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          tags: webnoise-builder
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Extract WASM and HTML
        run: |
          mkdir out
          docker run --rm -v ${{ github.workspace }}/out:/out webnoise-builder bash -c "\
          cp /app/build/webnoise.wasm /out/ && \
          cp /app/build/webnoise.js /out/ && \
          cp /app/build/webnoise.html /out/index.html"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out